#!/usr/bin/env python3
"""
Pytest Configuration and Fixtures

Shared fixtures and configuration for the test suite.

Copyright (c) 2025 AryanVBW
"""

import os
import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


# ==============================================================================
# Configuration
# ==============================================================================

def pytest_configure(config):
    """Configure pytest."""
    # Register markers
    config.addinivalue_line("markers", "slow: marks tests as slow")
    config.addinivalue_line("markers", "integration: marks tests as integration tests")
    config.addinivalue_line("markers", "unit: marks tests as unit tests")
    config.addinivalue_line("markers", "gui: marks tests that require GUI")
    config.addinivalue_line("markers", "network: marks tests that require network access")


def pytest_collection_modifyitems(config, items):
    """Modify test collection."""
    # Skip slow tests unless --runslow is passed
    if not config.getoption("--runslow", default=False):
        skip_slow = pytest.mark.skip(reason="need --runslow option to run")
        for item in items:
            if "slow" in item.keywords:
                item.add_marker(skip_slow)

    # Skip network tests in offline mode
    if os.environ.get("OFFLINE_MODE"):
        skip_network = pytest.mark.skip(reason="network tests disabled in offline mode")
        for item in items:
            if "network" in item.keywords:
                item.add_marker(skip_network)


def pytest_addoption(parser):
    """Add custom command line options."""
    parser.addoption(
        "--runslow",
        action="store_true",
        default=False,
        help="Run slow tests",
    )
    parser.addoption(
        "--integration",
        action="store_true",
        default=False,
        help="Run integration tests",
    )


# ==============================================================================
# Fixtures
# ==============================================================================

@pytest.fixture
def project_root() -> Path:
    """Return the project root directory."""
    return PROJECT_ROOT


@pytest.fixture
def configs_dir(project_root) -> Path:
    """Return the configs directory."""
    return project_root / "auto_blogger" / "configs"


@pytest.fixture
def temp_config_dir(tmp_path) -> Path:
    """Create a temporary config directory."""
    config_dir = tmp_path / "configs"
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


@pytest.fixture
def sample_config() -> dict:
    """Return a sample configuration dictionary."""
    return {
        "wordpress_url": "https://example.com",
        "wordpress_username": "test_user",
        "wordpress_password": "test_password",
        "gemini_api_key": "test_gemini_key",
        "openai_api_key": "test_openai_key",
        "source_url": "https://source.example.com",
        "article_link_selector": "article a.title",
        "article_title_selector": "h1.article-title",
        "article_content_selector": "div.article-content",
    }


@pytest.fixture
def sample_article() -> dict:
    """Return a sample article dictionary."""
    return {
        "title": "Test Article Title",
        "content": "<p>This is the test article content.</p>",
        "url": "https://source.example.com/test-article",
        "author": "Test Author",
        "date": "2025-01-15",
    }


@pytest.fixture
def mock_selenium_driver():
    """Create a mock Selenium WebDriver."""
    driver = MagicMock()
    driver.get.return_value = None
    driver.find_element.return_value = MagicMock()
    driver.find_elements.return_value = []
    driver.page_source = "<html><body>Test</body></html>"
    driver.quit.return_value = None
    return driver


@pytest.fixture
def mock_requests_session(mocker):
    """Create a mock requests session."""
    session = mocker.patch("requests.Session")
    mock_response = MagicMock()
    mock_response.status_code = 200
    mock_response.json.return_value = {"id": 1, "link": "https://example.com/post/1"}
    mock_response.text = "<html><body>Test</body></html>"
    session.return_value.get.return_value = mock_response
    session.return_value.post.return_value = mock_response
    return session


@pytest.fixture
def mock_gemini_client(mocker):
    """Create a mock Gemini AI client."""
    mock_model = MagicMock()
    mock_response = MagicMock()
    mock_response.text = "This is paraphrased content generated by AI."
    mock_model.generate_content.return_value = mock_response

    mocker.patch("google.generativeai.configure")
    mocker.patch("google.generativeai.GenerativeModel", return_value=mock_model)

    return mock_model


@pytest.fixture
def mock_openai_client(mocker):
    """Create a mock OpenAI client."""
    mock_client = MagicMock()
    mock_image = MagicMock()
    mock_image.url = "https://example.com/generated-image.png"
    mock_client.images.generate.return_value.data = [mock_image]

    mocker.patch("openai.OpenAI", return_value=mock_client)

    return mock_client


@pytest.fixture
def mock_wordpress_api(mocker):
    """Create a mock WordPress API client."""
    mock_response = MagicMock()
    mock_response.status_code = 201
    mock_response.json.return_value = {
        "id": 123,
        "title": {"rendered": "Test Post"},
        "link": "https://example.com/test-post",
        "status": "draft",
    }

    mocker.patch("requests.post", return_value=mock_response)
    mocker.patch("requests.get", return_value=mock_response)

    return mock_response


# ==============================================================================
# Environment Fixtures
# ==============================================================================

@pytest.fixture
def clean_environment(monkeypatch):
    """Ensure a clean environment for tests."""
    # Clear relevant environment variables
    env_vars = [
        "WORDPRESS_URL",
        "WORDPRESS_USERNAME",
        "WORDPRESS_APP_PASSWORD",
        "GEMINI_API_KEY",
        "OPENAI_API_KEY",
        "AUTO_BLOGGER_DEBUG",
    ]
    for var in env_vars:
        monkeypatch.delenv(var, raising=False)


@pytest.fixture
def debug_environment(monkeypatch):
    """Set up debug environment."""
    monkeypatch.setenv("AUTO_BLOGGER_DEBUG", "1")
    monkeypatch.setenv("LOG_LEVEL", "DEBUG")


# ==============================================================================
# Skip Conditions
# ==============================================================================

requires_network = pytest.mark.skipif(
    os.environ.get("OFFLINE_MODE") == "1",
    reason="Requires network access",
)

requires_gui = pytest.mark.skipif(
    os.environ.get("DISPLAY") is None and sys.platform != "darwin" and sys.platform != "win32",
    reason="Requires display for GUI tests",
)

requires_chrome = pytest.mark.skipif(
    not any([
        Path("/Applications/Google Chrome.app").exists(),
        Path("/usr/bin/google-chrome").exists(),
        Path("/usr/bin/chromium").exists(),
        Path("C:/Program Files/Google/Chrome/Application/chrome.exe").exists(),
    ]),
    reason="Requires Chrome/Chromium browser",
)
